@RestaurantReservation.WebApi_HostAddress = http://localhost:5003

POST {{RestaurantReservation.WebApi_HostAddress}}/api/user/login
Content-Type: application/json

{
  "email": "teste@teste.com.br",
  "password": "Teste@1234"
}

###

POST {{RestaurantReservation.WebApi_HostAddress}}/api/user/register
Content-Type: application/json

{
  "email": "teste2@teste.com.br",
  "password": "Teste@1234",
  "passwordconfirmation": "Teste@1234"
}

###


POST {{RestaurantReservation.WebApi_HostAddress}}/api/user/refresh-login

###

POST {{RestaurantReservation.WebApi_HostAddress}}/api/reservations/make
Content-Type: application/json

{
  //MakeReservationRequest
}

###

GET {{RestaurantReservation.WebApi_HostAddress}}/api/businesshours

###

POST {{RestaurantReservation.WebApi_HostAddress}}/api/businesshours
Content-Type: application/json

{
  //CreateBusinessHoursRuleRequest
}

###

DELETE {{RestaurantReservation.WebApi_HostAddress}}/api/businesshours/{id:guid}

###

GET {{RestaurantReservation.WebApi_HostAddress}}/api/businesshours/{id:guid}

###

PUT {{RestaurantReservation.WebApi_HostAddress}}/api/businesshours/{id:guid}
Content-Type: application/json

{
  //UpdateBusinessHoursRuleRequest
}

###

DELETE {{RestaurantReservation.WebApi_HostAddress}}/api/reservation

###

POST {{RestaurantReservation.WebApi_HostAddress}}/api/reservation/make-reservation
Content-Type: application/json

{
  //MakeReservationRequest
}

###

GET {{RestaurantReservation.WebApi_HostAddress}}/api/table

###

POST {{RestaurantReservation.WebApi_HostAddress}}/api/table
Content-Type: application/json

{
  //CreateTableRequest
}

###

DELETE {{RestaurantReservation.WebApi_HostAddress}}/api/table/{id:guid}

###

GET {{RestaurantReservation.WebApi_HostAddress}}/api/table/{id:guid}

###

PATCH {{RestaurantReservation.WebApi_HostAddress}}/api/table/{id:guid}
Content-Type: application/json

{
  //UpdateTableRequest
}

###
